name: life-sports-club
region: fra
services:
  - name: web
    image:
      registry_type: DOCR
      repository: life-sports-club
      tag: latest
    http_port: 8080
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    health_check:
      http_path: /health
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
databases:
  - name: db
    engine: PG
    production: false
